name: Strategy Test

on:
  push:
    paths:
      - 'strategies/**' 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.14'  # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run strategy test
      run: |
        python test.py

    - name: Report test results
      if: failure()
      run: |
        echo "Strategy test failed!"
